/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dublinsmartbubble;

import javax.swing.JOptionPane;

/**
 *
 * @author Seán
 */
public class SmartBubbleGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SmartBubbleGUI.class.getName());

    SmartBubbleQueue smartQ = new SmartBubbleQueue();
    SmartBubbleSLL smartSLL = new SmartBubbleSLL();
    SmartBubbleStack smartStack = new SmartBubbleStack();
    /**
     * Creates new form SmartBubbleGUI
     */
    public SmartBubbleGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLBL = new javax.swing.JLabel();
        detailLBL = new javax.swing.JLabel();
        detailTF = new javax.swing.JTextField();
        sizeLBL = new javax.swing.JLabel();
        sizeTF = new javax.swing.JTextField();
        addBTN = new javax.swing.JButton();
        startBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        statTA = new javax.swing.JTextArea();
        statLBL = new javax.swing.JLabel();
        searchBTN = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        searchTA = new javax.swing.JTextArea();
        deleteBTN = new javax.swing.JButton();
        sizeEXLBL = new javax.swing.JLabel();
        statsBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLBL.setBackground(new java.awt.Color(255, 255, 255));
        titleLBL.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        titleLBL.setForeground(new java.awt.Color(0, 0, 0));
        titleLBL.setText("Dublin Smart Bubble");

        detailLBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        detailLBL.setText("Enter Debris Detail :");

        sizeLBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sizeLBL.setText("Debris Size :");

        addBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addBTN.setText("ADD");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });

        startBTN.setBackground(new java.awt.Color(0, 102, 102));
        startBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        startBTN.setText("Start Process");
        startBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBTNActionPerformed(evt);
            }
        });

        statTA.setColumns(20);
        statTA.setRows(5);
        jScrollPane1.setViewportView(statTA);

        statLBL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        statLBL.setText("Waste Statistics");

        searchBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchBTN.setText("Search");
        searchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTNActionPerformed(evt);
            }
        });

        searchTA.setColumns(20);
        searchTA.setRows(5);
        jScrollPane2.setViewportView(searchTA);

        deleteBTN.setBackground(new java.awt.Color(255, 0, 0));
        deleteBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteBTN.setForeground(new java.awt.Color(255, 255, 255));
        deleteBTN.setText("Delete");
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });

        sizeEXLBL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sizeEXLBL.setText("e.g(Small,Med,Large)");

        statsBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        statsBTN.setText("Show Stats");
        statsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statsBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(detailLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(statsBTN)
                .addGap(45, 45, 45)
                .addComponent(statLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
            .addGroup(layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(titleLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchBTN)
                            .addComponent(deleteBTN)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addComponent(addBTN))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(sizeLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sizeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(95, 95, 95)
                                        .addComponent(startBTN)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sizeEXLBL)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(detailLBL)
                            .addComponent(detailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sizeLBL)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(sizeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sizeEXLBL)))
                        .addGap(18, 18, 18)
                        .addComponent(addBTN)
                        .addGap(18, 18, 18)
                        .addComponent(startBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(deleteBTN)
                                .addGap(18, 18, 18)
                                .addComponent(searchBTN))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(statLBL)
                            .addComponent(statsBTN))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
         
     String debrisType = detailTF.getText();
        String size = sizeTF.getText();
        
        if(debrisType.isEmpty() || size.isEmpty()) 
            return;

        DebrisType debris = new PlasticDebris(debrisType, size);
        smartQ.add(debris);
        searchTA.append("Added to the queue: " + debris.getDescription() + "\n");

        detailTF.setText("");
        sizeTF.setText("");
    
    }//GEN-LAST:event_addBTNActionPerformed

    private void startBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBTNActionPerformed

           DebrisType fromQueue = smartQ.remove();
        if(fromQueue != null) {
            smartStack.add(fromQueue);
            searchTA.append("Moved to the stack: " + fromQueue.getDescription() + "\n");

            DebrisType fromStack = smartStack.remove();
            if(fromStack != null) {
                smartSLL.add(fromStack);
                searchTA.append("Stored in list: " + fromStack.getDescription() + "\n");
            }
        } else {
            searchTA.append("Queue is empty" + "\n");
        }
    
    }//GEN-LAST:event_startBTNActionPerformed

    private void searchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTNActionPerformed
        String searchText = JOptionPane.showInputDialog(null,  "Search for debris:");
        
        if(searchText != null && searchText.isEmpty()) {
            boolean found = smartSLL.search(searchText);
            if(found) {
                 searchTA.append(searchText + " found " + "\n");
            } else {
                 searchTA.append(searchText + " not found" + "\n");
            }
        }
    }//GEN-LAST:event_searchBTNActionPerformed

    private void statsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statsBTNActionPerformed
       statTA.setText("");
        statTA.append("Queue:\n" + smartQ + "\n");
        statTA.append("Stack:\n" + smartStack + "\n");
        statTA.append("Linked List:\n" + smartSLL + "\n");
    
        
    }//GEN-LAST:event_statsBTNActionPerformed

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
       String debrisType = JOptionPane.showInputDialog(this, "Enter debris type to delete:");
        if(debrisType != null && debrisType.isEmpty()) {
            
            boolean removed = smartSLL.remove(debrisType);
            if(removed) {
                 searchTA.append(debrisType + " removed"  + "\n");
            } else {
                searchTA.append(debrisType + " not found" + "\n");
            }
        }
    
   
    }//GEN-LAST:event_deleteBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBTN;
    private javax.swing.JButton deleteBTN;
    private javax.swing.JLabel detailLBL;
    private javax.swing.JTextField detailTF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton searchBTN;
    private javax.swing.JTextArea searchTA;
    private javax.swing.JLabel sizeEXLBL;
    private javax.swing.JLabel sizeLBL;
    private javax.swing.JTextField sizeTF;
    private javax.swing.JButton startBTN;
    private javax.swing.JLabel statLBL;
    private javax.swing.JTextArea statTA;
    private javax.swing.JButton statsBTN;
    private javax.swing.JLabel titleLBL;
    // End of variables declaration//GEN-END:variables
}
